apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  env: preprod

namespace: preprod
namePrefix: preprod-

patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: nginx
  path: ingress-json-patch.yaml

